### ISSUE TITLE
Problem with Quickstart step 3.

### ISSUE THREAD

**Issue by fialhocoelho** [HSF-reco-and-software-triggers/Tracking-ML-Exa.TrkX#7]
When I’m trying to run the [step 3. from quickstart](https://github.com/HSF-reco-and-software-triggers/Tracking-ML-Exa.TrkX/blob/master/docs/pipelines/quickstart.md#3-running-the-pipeline), the following error returns:
```
Traceback (most recent call last):

  File "run_pipeline.py", line 113, in <module>
    main(run_args)
  File "run_pipeline.py", line 86, in main
    model_config = load_config(stage, resume_id, project_config)
  File "Tracking-ML-Exa.TrkX/src/Pipelines/TrackML_Example/utils/config_utils.py", line 53, in load_config
    with open(stage_config_file) as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Checking the error, the function [load_config()](https://github.com/HSF-reco-and-software-triggers/Tracking-ML-Exa.TrkX/blob/06240b720636d8e45776ca0c898d09e2c63ce993/src/Pipelines/TrackML_Example/utils/config_utils.py#L44)   tries to open a config file with a invalid (`None`) path generated by [find_config()](https://github.com/HSF-reco-and-software-triggers/Tracking-ML-Exa.TrkX/blob/06240b720636d8e45776ca0c898d09e2c63ce993/src/Pipelines/TrackML_Example/utils/config_utils.py#L39).

I believe the function [find_config()](https://github.com/HSF-reco-and-software-triggers/Tracking-ML-Exa.TrkX/blob/06240b720636d8e45776ca0c898d09e2c63ce993/src/Pipelines/TrackML_Example/utils/config_utils.py#L39) returns `None` because the parameter `model_library`   in some paths in the configuration files `*.yml` are set to: `/global/homes/d/danieltm/ExaTrkX/Tracking-ML-Exa.TrkX/src/Pipelines/Examples/LightningModules` 

E.g.:
https://github.com/HSF-reco-and-software-triggers/Tracking-ML-Exa.TrkX/blob/06240b720636d8e45776ca0c898d09e2c63ce993/src/Pipelines/TrackML_Example/configs/pipeline_default.yaml#L1

**Comment by a-akram** [comment]
Did you manage to run the [step 3. from quickstart](https://github.com/HSF-reco-and-software-triggers/Tracking-ML-Exa.TrkX/blob/master/docs/pipelines/quickstart.md#3-running-the-pipeline)?
